version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  # node: circleci/node@5.0

jobs:
  setup:
    docker:
      - image: denoland/deno:latest
    # executor:
    # name: node/default
    # tag: "14.17.1"
    steps:
      - checkout
      # - node/install-packages:
      # pkg-manager: yarn
      - run:
          name: Generate config
          command: pwd
          # command: ./scripts/circleci-config.ts
      - continuation/continue:
          configuration_path: main.yml

workflows:
  setup:
    jobs:
      - setup
