version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  node: circleci/node@5.0

jobs:
  setup:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Generate config
          command: ./scripts/circleci-config.mjs
      - continuation/continue:
          configuration_path: main.yml

workflows:
  setup:
    jobs:
      - setup
